### ISSUE TITLE
Adding warnings raises PreCommit::NotAnArray error

### ISSUE THREAD

**Issue by arrancscott** [jish/pre-commit#199]
Adding warnings using the syntax - `git config pre-commit.warnings 'rubocop, jshint'` and then running `pre-commit list` returns the following error:

`/Library/Ruby/Gems/2.0.0/gems/pre-commit-0.22.1/lib/pre-commit/configuration.rb:23:in 'get_arr': PreCommit::NotAnArray (PreCommit::NotAnArray)`

If you add them using the following syntax - `git config pre-commit.warnings '[rubocop, jshint]'` it works.

**Comment by mpapis** [comment]
could you please open a pull request for documentation => https://github.com/jish/pre-commit#enabling--disabling-checks--warnings

**Comment by arrancscott** [comment]
Can this be closed now?

**Comment by jish** [comment]
Looks like it. Thanks. :)
