### ISSUE TITLE
puppet plugin

### ISSUE THREAD

**Issue by robinbowes** [jish/pre-commit#202]
I took the liberty of creating a puppet plugin based on your php plugin.

https://github.com/yo61/pre-commit-puppet

Feel free to snaffle it and add it to the pre-commit-plugins org.

I shall be adding support for puppet-lint, either as a separate plugin or incorporating it in this plugin some time in the future.

**Comment by jish** [comment]
Added to the wiki https://github.com/jish/pre-commit/wiki/Plugins

We can leave this open if we are intending to bring it into the `pre-commit-plugins` org.

**Comment by robinbowes** [comment]
I just pushed to the pre-commit-plugins org. Might as well close this now?
