### ISSUE TITLE
No check for byebug

### ISSUE THREAD

**Issue by prpetten** [jish/pre-commit#206]
byebug is the new debugging standard for ruby 2.x, and adding 'byebug' to a file works just like dropping in a 'debugger' in ruby 1.x.  

byebug github repo:
https://github.com/deivid-rodriguez/byebug

Would like to check for 'byebug' as well as 'debugger'

**Comment by Fryie** [comment]
i second this :)

**Comment by mpapis** [comment]
closing in favour of #207

**Comment by jish** [comment]
https://github.com/jish/pre-commit/pull/224
