### ISSUE TITLE
       "Could not find plugin supporting js_hint / JsHint"

### ISSUE THREAD

**Issue by rivertam** [jish/pre-commit#223]
I'm getting the following from `pre-commit list`

    Could not find plugin supporting js_hint / JsHint,
    available plugins: BeforeAll, Ci, Closure, Coffeelint, Common, ConsoleLog, Csslint, Debugger, GemfilePath, Go, Jshint, Jslint, Json, Local, MergeConflict, Migration, NbSpace, Pry, Rails, RspecFocus, Rubocop, Ruby, RubySymbolHashrockets, ScssLint, Tabs, Whitespace, Yaml
     Available providers: default(0) git(10) git_old(11) yaml(20) env(30)
     Available checks   : before_all ci closure coffeelint common console_log csslint debugger gemfile_path go jshint jslint json local merge_conflict migration nb_space pry rails rspec_focus rubocop ruby ruby_symbol_hashrockets scss_lint tabs whitespace yaml
     Default   checks   : common rails
     Enabled   checks   : common rails ruby debugger
     Evaluated checks   : tabs nb_space whitespace merge_conflict debugger pry local console_log migration pry local debugger
     Default   warnings : 
     Enabled   warnings : console_log whitespace
     Evaluated warnings : console_log whitespace

It seems to me that I'm not trying to load js_hint ever, so I don't know why it's saying that it couldn't find a plugin supporting js_hint. This error message comes up every time I commit.

**Comment by mpapis** [comment]
Did you configure is_hint somewhere? The included check is without
underscore.

**Comment by rivertam** [comment]
I didn't really configure anything. Everything I've done has been via command line arguments to `pre-commit`.

**Comment by rivertam** [comment]
I'm even doing `pre-commit install default` which should overwrite everything, right? I have no idea where it's getting this `js_hint` stuff.

**Comment by rivertam** [comment]
Okay, I figured it out: it was in my `.git/config` file in a `remove` variable.

**Comment by jish** [comment]
Cool. I'm glad you were able to sort it out! :)
