### ISSUE TITLE
Checks fail to start due to judged a binary file

### ISSUE THREAD

**Issue by kyoshidajp** [jish/pre-commit#238]
Hi.

I want to check my Ruby file by rubocop. But check didn't work when I commit it.

That file body is the following.

```ruby
# コメント
def sample
  # comment
  # comment
  # comment
end
```

However next file is worked well.

```ruby
# コメント
def sample
  # comment
  # comment
end
```

I guess the reason why is because `binary?` method of `PreCommit::Utils::StagedFiles` module is "best guess".

So, I suggest that add not-binary list file and `binary?` method return `false` when argument file is found in that list file. The list file support specified pattern, like a .gitignore.

Or support check include binary file option, for example a environment variable.

**Comment by mpapis** [comment]
we could extend the binary check to exclude unicode letters too ... do you want to take a shoot at it?

**Comment by kyoshidajp** [comment]
I'm afraid if excluded unicode letters, [Rubocop::Cop::Style::AsciiComments](http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/AsciiComments) wouldn't work.

**Comment by kyoshidajp** [comment]
I was wrong. Exclude unicode letters only `binary?`, then it is good for me.

**Comment by kyoshidajp** [comment]
How about using `.binary?` method in [mime-types](https://github.com/mime-types/ruby-mime-types).

This gem require target files have filename extension. And still not completely correct. For example, file name is `sample.rb` even though PNG file.

However this behavior enough for my case.

**Comment by jish** [comment]
Resolved in https://github.com/jish/pre-commit/pull/240
