### ISSUE TITLE
Unable to install versions of 0.27.0 and 0.28.0

### ISSUE THREAD

**Issue by rlgreen91** [jish/pre-commit#241]
Hello,

I am unable to install versions 0.27.0 and 0.28.0 of the gem.  Each time I try to install them using the `gem install` command, I get the following errors: 

`ERROR:  While executing gem ... (Errno::EINVAL)
    Invalid argument @ rb_sysopen - C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/pre-commit-0.28.0/templates/gem/<%= gem_name %>.gemspec`

`ERROR:  While executing gem ... (Errno::EINVAL)
    Invalid argument @ rb_sysopen - C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/pre-commit-0.27.0/templates/gem/<%= gem_name %>.gemspec`

I am running Ruby 2.3 and Rails 5.0 on Windows 8 x64.

**Comment by jish** [comment]
Hi @rlgreen91 

I unfortunately do not have a Windows computer to test on, so I'm not sure I can reproduce your issue. Could you give me the command you are trying to run?

Is it `gem install pre-commit`? `pre-commit install`?

@mpapis have you seen something like this before? Is it maybe due to spaces in the template filenames or something?

**Comment by rlgreen91** [comment]
@jish I used the commands `gem install pre-commit` and `gem install pre-commit '0.27.0'`.  I had to drop back to 0.26.0 to install it successfully.

**Comment by mpapis** [comment]
looks like `ERB` evaluation of paths did not work, unfortunately I'm pretty busy this week, please ping me if I do not respond till next Monday evening.

**Comment by jish** [comment]
I have released version `0.29.0` which _I think_ should solve the issue. Again, I do not have a Windows machine to test this on, so please let me know if this resolves your issue. :)

Sorry for the delay.

**Comment by rlgreen91** [comment]
Hey @jish - no worries about the delay!  I will try to install that version this weekend and let you know the outcome.
