### ISSUE TITLE
Don`t work with SourceTree

### ISSUE THREAD

**Issue by dluhhbiu** [jish/pre-commit#246]
At the time of the commit SourceTree displays a message:
`.git/hooks/pre-commit: line 29: bundle: command not found`
mac os: 10.12.1
sourcetree: 2.3.2

**Comment by dluhhbiu** [comment]
https://gist.github.com/dluhhbiu/263e3970e38bf3b98091cd610da91ea8

**Comment by jish** [comment]
I'm glad you got everything working! Would you like me to add that as an installable hook that could be installed with:

    pre-commit install --sourcetree

It is as simple as adding a new file in `templates/hooks/` https://github.com/jish/pre-commit/tree/493b55b86577fa89f34f7ace4ad132a467abecd2/templates/hooks

**Comment by ameyab10** [comment]
I am seeing still seinng this, anything I can do

**Comment by jish** [comment]
We did add the source-tree specific hook in November 2016. https://github.com/jish/pre-commit/blob/b3a653eb063d890dd7277265746da4da6a8d47ab/templates/hooks/sourcetree

I do not have source tree installed so unfortunately I am unable to help debug your issue.

You could try adding some logging to the hook (If yo used the command above `pre-commit install --sourcetree`) It should be located at `.git/hooks/pre-commit`.

It also looks like that hook was written specifically for use with RVM. Do you use RVM or some other Ruby version manager? 🤔
