### ISSUE TITLE
how to run rubocop against changes in non-.rb files

### ISSUE THREAD

**Issue by lwille** [jish/pre-commit#274]
One of my projects has some executables which lack the `.rb` extension. These files are not matched by `pre-commit`.

In my old "manual" hook setup I was using `file -I` which reliably detects the exact mime type of executable files if they have a proper shebang:

```bash
➜ file -I bin/pre-commit
bin/pre-commit: text/x-ruby; charset=us-ascii
```

- add configuration option to map Mime types -> plugin
- mime-matching is opt-in by default
- ensure portability of type detection
- can be implemented as plugin that sends file lists to other plugins

What do people think about this?

**Comment by jish** [comment]
Hi @lwille,

The only thing I would be worried about here is degrading performance. So if the matching is opt-in by default, then I believe it should be safe to include without affecting out-of-the-box performance.
