### ISSUE TITLE
Could you release a new version?

### ISSUE THREAD

**Issue by machisuke** [jish/pre-commit#286]
@jish 

There are some changes still not published to RubyGems. https://github.com/jish/pre-commit/compare/v0.39.0...master

Especially, https://github.com/jish/pre-commit/pull/283 is important since `File.exists?` has been removed from Ruby 3.2.

**Comment by jish** [comment]
Thanks for the reminder! 😄

Released `0.40.0` https://rubygems.org/gems/pre-commit/versions/0.40.0
