### ISSUE TITLE
PHP_CodeSniffer pre-commit hook

### ISSUE THREAD

**Issue by mikedfunk** [jish/pre-commit#54]
It would be great if I could test my PHP code to PSR2 standards via pre-commit. [Here is a git repo](https://github.com/s0enke/git-hooks/tree/master/phpcs-pre-commit) that already does this, but I couldn't figure out how to apply that check in addition to all the stuff from the pre-commit repo.

**Comment by mpapis** [comment]
closing as there was no feedback in over two months, please let us know if you can provide more details and we will reopen
