### ISSUE TITLE
Use bundler for RuboCop

### ISSUE THREAD

**Issue by jgarber** [jish/pre-commit#83]
In my project, we've locked to a specific version of RuboCop in the Gemfile, but pre-commit doesn't seem to respect that.

**Comment by m1foley** [comment]
I'd like to re-open this issue; I'm having the same problem as the original poster.

**Comment by mpapis** [comment]
@m1foley try using your project ruby, here are some instructions that might help: https://github.com/jish/pre-commit#rvm

**Comment by m1foley** [comment]
That doesn't work for me. I use rbenv + Bundler.

**Comment by mpapis** [comment]
@m1foley the instructions to set custom ruby are the same for any kind of ruby, ruby manager ... or anything you want to use, please refer your tool documentation for instructions how to use ruby of your choosing.

when you get a proper command working please either open a PR to add it to readme or share it with us so we can add it.

**Comment by m1foley** [comment]
I've found a way to do it and added a PR. Thanks for your help & patience.
